apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homarr
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: homarr
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  sources:
    - repoURL: 'https://homarr-labs.github.io/charts'
      chart: homarr
      targetRevision: 8.4.3
      helm:
        valueFiles:
          - $values/values/homarr/values.yaml

    - repoURL: 'https://github.com/mz4p/homelab-gitops.git'
      targetRevision: HEAD
      ref: values
