homepage:
  service:
    main:
      type: ClusterIP
      ports:
        http:
          port: 80
          targetPort: 3000
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      hosts:
        - host: homepage.local
          paths:
            - path: /
              pathType: Prefix
  env:
    - name: HOMEPAGE_ALLOWED_HOSTS
      value: "homepage.local,192.168.0.100,localhost"

  config:
    settings:
      title: "K3s Homelab"
      headerStyle: clean
    
    services:
      - Infrastructure:
          - ArgoCD:
              icon: argocd.png
              href: "http://argocd.local"
              description: GitOps Controller
