homepage:
  service:
    main:
      type: ClusterIP
      ports:
        http:
          port: 3000
  config:
    title: "K3s Homelab"
    headerStyle: clean
    services:
      - Infrastructure:
        - ArgoCD:
            icon: argocd
            href: "https://argocd.local"
            description: GitOps Controller
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
  env:
    - name: HOMEPAGE_ALLOWED_HOSTS
      value: "homepage.local,192.168.0.100,localhost"
      hosts:
        - host: homepage.local
          paths:
            - path: /
              pathType: Prefix
