apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-route
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: http
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`argocd.local`)
      kind: Rule
      services:
        - name: argocd-gitops-server
          port: 80
