apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-force-fix
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`argocd.local`)
      kind: Rule
      services:
        - name: argocd-gitops-server
          port: 80
