argo-cd:
  configs:
    params:
      server.insecure: true
  server:
    host: argocd.local
    ingress:
      enabled: false
    ingressRoute:
      enabled: true
      router:
        entryPoints:
          - web
        tls: {}
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
        traefik.ingress.kubernetes.io/service.serversscheme: http
      hosts:
        - argocd.local
