argo-cd:
  configs:
    params:
      server.insecure: true
  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
          traefik.ingress.kubernetes.io/service.serversscheme: http
          traefik.ingress.kubernetes.io/router.entrypoints: web
      hosts:
        - argocd.local
